language: c

before_install:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam

install:
  - export OPAMYES=1

  - opam init
  - eval `opam config env`
  - opam switch
  - opam update
  - opam install async async_ssl cohttp cryptokit yojson

script:
  - opam pin add .
  - opam unpin git-lfs-server
  - ./scripts/test_build.sh src/lfs_server.native

