language: c

before_install:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam

install:
  - export OPAMYES=1

  - opam init
  - opam switch 4.02.3
  - eval `opam config env`
  - opam update
  - opam install async async_ssl cohttp cryptokit yojson simple_pam
  - opam install bisect ocveralls ocamldiff

script:
  - opam pin add .
  - opam unpin git-lfs-server
  - ./scripts/run_tests.sh

after_success:
  - ocveralls --prefix _build _build/coverage*.out --send

