language: c

before_install:
  - sudo add-apt-repository ppa:avsm/ppa
  - sudo apt-get update
  - sudo apt-get install ocaml ocaml-native-compilers camlp4-extra opam

install:
  - opam --version

  - ~/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
  - eval `opam config env`
  - opam switch
  - opam update
  - opam install async async_ssl cohttp cryptokit

script:
  - ./scripts/build.sh lfs_server.native

